export const t = {
    english: {
        "Hello": "Hello",
        "Wheat": "Wheat",
        "Bajra": "Bajra",
        "Weather Condition": "Weather Condition",
        "Temperature": "Temperature",
        "Humidity": "Humidity",
        "Moisture": "Moisture",
        "Monday": "Monday",
        "Tuesday": "Tuesday",
        "Wednesday": "Wednesday",
        "Thursday": "Thursday",
        "Friday": "Friday",
        "Saturday": "Saturday",
        "Sunday": "Sunday",
        "January": "January",
        "February": "February",
        "March": "March",
        "April": "April",
        "May": "May",
        "June": "June",
        "July": "July",
        "August": "August",
        "September": "September",
        "October": "October",
        "November": "November",
        "December": "December",
        "Language": "Language",
        "Choose": "Choose",
        "line1": "Smart farming in your language! Get crop info, weather updates, and market prices easily",
        "line2": "Real-time info on soil health, plant growth, and weather patterns. Available in multiple languages for easy use.",
        "line3": "",
        "Get Started": "Get Started",
        "Login": "Login",
        "Phone Number": "Phone Number",
        "Send OTP": "Send OTP",
        "Acidity": "Acidity",
        "Nitrogen": "Nitrogen",
        "Potassium": "Potassium",
        "Phosphorous": "Phosphorous",
        "Plant Health": "Plant Health",
        "Next":"Next",
        "Krishi Junction":"Krishi Junction",
        "Km/h":"Km/h",
        "Current Task":"Current Tasks",
        "Due":"Due",
        "Left":"Left",
        "Homepage":"Homepage",
        "Dashboard":"Dashboard",
        "Shopping":"Shopping",
        "Chat":"Chat",
        "Account":"Account",
        "Irrigation":"Irrigation",
        "Required":"Required",
        "Modules":"Modules",
        "Macro Nutrients":"Macro Nutrients",
        "Micro Nutrients":"Micro Nutrients",
        "Crop Status":"Crop Status",
        "Suggestions":"Suggestions",
        "Carbon":"Carbon",
        "Copper":"Copper",
        "Calcium":"Calcium",
        "Magnesium":"Magnesium",
        "Chat":"Chat",
        "Drone Control":"Drone Control",
        "Search":"Search",
        "Greet":"Hello Farmer! I am agribot. How may I help you?",
        "Friend":"Friend",
        "Profile":"Profile",
    },
    hindi:{
        "Hello": "नमस्ते",
        "Wheat": "गेहूँ",
        "Bajra": "बाजरे",
        "Weather Condition": "मौसम",
        "Temperature": "तापमान",
        "Humidity": "आर्द्रता",
        "Moisture": "नमी",
        "Monday": "सोमवार",
        "Tuesday": "मंगलवार",
        "Wednesday": "बुधवार",
        "Thursday": "गुरुवार",
        "Friday": "शुक्रवार",
        "Saturday": "शनिवार",
        "Sunday": "रविवार",
        "January": "जनवरी",
        "February": "फ़रवरी",
        "March": "मार्च",
        "April": "अप्रैल",
        "May": "मई",
        "June": "जून",
        "July": "जुलाई",
        "August": "अगस्त",
        "September": "सितंबर",
        "October": "अक्टूबर",
        "November": "नवंबर",
        "December": "दिसंबर",
        "Language": "भाषा",
        "Choose": "चुनें",
        "line1": "आपकी भाषा में स्मार्ट खेती! फसल की जानकारी, मौसम के अपडेट और बाजार मूल्य आसानी से प्राप्त करें|",
        "line2": "मिट्टी के स्वास्थ्य, पौधों की वृद्धि और मौसम के पैटर्न पर वास्तविक समय की जानकारी। आसान उपयोग के लिए कई भाषाओं में उपलब्ध|",
        "line3": "",
        "Get Started": "शुरू करें",
        "Login": "लॉग इन",
        "Phone Number": "फ़ोन नंबर",
        "Send OTP": "OTP भेजें",
        "Acidity": "अम्लता",
        "Nitrogen": "नाइट्रोजन",
        "Potassium": "पोटैशियम",
        "Phosphorous": "फास्फोरस",
        "Plant Health": "पौधों का स्वास्थ्य",
        "Next":"अगला",
        "Krishi Junction":"कृषि जंक्शन",
        "Km/h":"कि.मी./घंटा",
        "Current Task":"वर्तमान कार्य",
        "Due":"देय",
        "Left":"शेष",
        "Homepage":"होमपेज",
        "Dashboard":"डैशबोर्ड",
        "Shopping":"खरीदारी",
        "Chat":"चैट",
        "Account":"खाता",
        "Irrigation":"सिंचाई",
        "Required":"आवश्यक",
        "Modules":"मॉड्यूल",
        "Macro Nutrients":"मैक्रो पोषक तत्व",
        "Micro Nutrients":"सूक्ष्म पोषक तत्व",
        "Crop Status":"फसल की स्थिति",
        "Suggestions":"सुझाव",
        "Carbon":"कार्बन",
        "Copper":"ताँबा",
        "Calcium":"कैल्शियम",
        "Magnesium":"मैगनीशियम",
        "Chat":"चैट",
        "Drone Control":"ड्रोन नियंत्रण",
        "Search":"खोज",
        "Greet":"नमस्ते! मैं एग्रीबॉट हूँ। आपकी कैसी सहायता कर सकता हूँ?",
        "Friend":"दोस्त",
        "Profile":"प्रोफ़ाइल",
    },
    tamil:{
        "Hello": "வணக்கம்",
        "Wheat": "கோதுமை",
        "Bajra": "பஜ்ரா",
        "Weather Condition": "வானிலை",
        "Temperature": "வெப்ப நிலை",
        "Humidity": "ஈரப்பதம்",
        "Moisture": "ஈரம்",
        "Monday": "திங்கட்கிழமை",
        "Tuesday": "செவ்வாய்",
        "Wednesday": "புதன்",
        "Thursday": "வியாழன்",
        "Friday": "வெள்ளி",
        "Saturday": "சனிக்கிழமை",
        "Sunday": "ஞாயிற்றுக்கிழமை",
        "January": "ஜனவரி",
        "February": "பிப்ரவரி",
        "March": "மார்ச்",
        "April": "ஏப்ரல்",
        "May": "மே",
        "June": "ஜூன்",
        "July": "ஜூலை",
        "August": "ஆகஸ்ட்",
        "September": "செப்டம்பர்",
        "October": "அக்டோபர்",
        "November": "நவம்பர்",
        "December": "டிசம்பர்",
        "Language": "மொழி",
        "Choose": "தேர்வு செய்",
        "line1": "உங்கள் மொழியில் ஸ்மார்ட் விவசாயம்! பயிர் தகவல், வானிலை அறிவிப்புகள் மற்றும் சந்தை விலைகளை எளிதாகப் பெறுங்கள்",
        "line2": "தாவர வளர்ச்சி மற்றும் மண் ஆரோக்கியத்திற்கு நேரடி தகவல், காற்பந்து முன்னேற்றங்களை எளிதாகப் பயன்படுத்த மொழிகளில் மற்றும் எளிய பயனுள்ள கையேடு செயலி கிடைக்கும்",
        "line3": "",
        "Get Started": "தொடங்குங்கள்",
        "Login": "உள் நுழைவு",
        "Phone Number": "தொலைபேசி எண்",
        "Send OTP": "OTP அனுப்பவும்",
        "Acidity": "அமிலத்தன்மை",
        "Nitrogen": "நைட்ரஜன்",
        "Potassium": "பொட்டாசியம்",
        "Phosphorous": "பாஸ்பரஸ்",
        "Plant Health": "தாவர ஆரோக்கியம்",
        "Next":"அடுத்து",
        "Krishi Junction":"கிருஷி ஜங்ஷன்",
        "Km/h":"கிமீ/ம.",
        "Current Task":"தற்போதைய பணி",
        "Due":"தேதி",
        "Left":"மீண்டும் உள்ள",
        "Homepage":"ஹோம்பேஜ்",
        "Dashboard":"டாஷ்போர்டு",
        "Shopping":"ஷாப்பிங்",
        "Chat":"உரையாடல்",
        "Account":"கணக்கு",
        "Irrigation":"நீர்ப்பாசனம்",
        "Required":"தேவை",
        "Modules":"தொகுதிகள்",
        "Macro Nutrients":"மேக்ரோநியூட்ரியண்ட்ஸ்",
        "Micro Nutrients":"நுண்ணூட்டச்சத்துக்கள்",
        "Crop Status":"பயிர் நிலை",
        "Suggestions":"பரிந்துரைகள்",
        "Carbon":"கார்பன்",
        "Copper":"செம்பு",
        "Calcium":"கால்சியம்",
        "Magnesium":"வெளிமம்",
        "Chat":"உரையாடல்",
        "Drone Control":"ட்ரோன் கட்டுப்பாடு",
        "Search":"தேடு",
        "Greet":"வணக்கம் விவசாயி! நான் அக்ரிபோட். நான் உங்களுக்கு எப்படி உதவ முடியும்?",
        "Friend":"நண்பர்",
        "Profile":"சுயவிவரம்",
    },
    telugu:{
        "Hello": "",
        "Wheat": "",
        "Bajra": "",
        "Weather Condition": "",
        "Temperature": "",
        "Humidity": "",
        "Moisture": "",
        "Monday": "",
        "Tuesday": "",
        "Wednesday": "",
        "Thursday": "",
        "Friday": "",
        "Saturday": "",
        "Sunday": "",
        "January": "",
        "February": "",
        "March": "",
        "April": "",
        "May": "",
        "June": "",
        "July": "",
        "August": "",
        "September": "",
        "October": "",
        "November": "",
        "December": "",
        "Language": "",
        "Choose": "",
        "line1": "",
        "line2": "",
        "line3": "",
        "Get Started": "",
        "Login": "",
        "Phone Number": "",
        "Send OTP": "",
        "Acidity": "",
        "Nitrogen": "",
        "Potassium": "",
        "Phosphorous": "",
        "Plant Health": "",
        "Next":"",
        "Krishi Junction":"",
        "Km/h":"",
        "Current Task":"",
        "Due":"",
        "Left (for ex: 2 days left, bracket wala part only for explanation)":"",
        "Homepage":"",
        "Dashboard":"",
        "Shopping":"",
        "Chat":"",
        "Account":"",
        "Irrigation":"",
        "Required":"",
        "Modules":"",
        "Macro Nutrients":"",
        "Micro Nutrients":"",
        "Crop Status":"",
        "Suggestions":"",
        "Carbon":"",
        "Copper":"",
        "Calcium":"",
        "Magnesium":"",
        "Chat":"",
        "Drone Control":"",
        "Search":"",
        "Greet":"",
        "Friend":"",
        "Profile":"",
    },
}